/*
Nombre: Minerva Melissa Trejo Gonzalez
Ejercicio 3
Tema 2
Crear un proyecto que implemente 6 métodos (funciones) para calcular 
el perimetro de 6 diferentes figuras.
*/
package formularioperimetrosfiguras;

import claselibreriaperimetrofiguras.libreriaperimetrofiguras;
public class formperimetrosfiguras extends javax.swing.JFrame {

    /**
     * Creates new form formperimetrosfiguras
     */
    public formperimetrosfiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3lado1 = new javax.swing.JLabel();
        jLabel4lado2 = new javax.swing.JLabel();
        jLabel5lado3 = new javax.swing.JLabel();
        jLabel6lado4 = new javax.swing.JLabel();
        jLabel7base = new javax.swing.JLabel();
        jLabel8altura = new javax.swing.JLabel();
        jTextField1lado1 = new javax.swing.JTextField();
        jTextField2lado2 = new javax.swing.JTextField();
        jTextField3lado3 = new javax.swing.JTextField();
        jTextField4lado4 = new javax.swing.JTextField();
        jTextField5base = new javax.swing.JTextField();
        jTextField6altura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5perimetro = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Triangulo rectangulo");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 71, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Cuadrado");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Rectangulo");
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Rombo");
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Romboide");
        jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton5ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Trapecio");
        jRadioButton6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton6ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Ejercicio 3. Programa que calcula el perimetro de 6 diferentes figuras geometricas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Tema 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel3lado1.setText("lado 1");
        getContentPane().add(jLabel3lado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel4lado2.setText("lado 2");
        getContentPane().add(jLabel4lado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel5lado3.setText("lado 3");
        getContentPane().add(jLabel5lado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel6lado4.setText("lado 4");
        getContentPane().add(jLabel6lado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 20));

        jLabel7base.setText("base");
        getContentPane().add(jLabel7base, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 40, 20));

        jLabel8altura.setText("altura");
        getContentPane().add(jLabel8altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, 30));

        jTextField1lado1.setText("0");
        getContentPane().add(jTextField1lado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 70, -1));

        jTextField2lado2.setText("0");
        getContentPane().add(jTextField2lado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 70, -1));

        jTextField3lado3.setText("0");
        getContentPane().add(jTextField3lado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 134, 70, -1));

        jTextField4lado4.setText("0");
        getContentPane().add(jTextField4lado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 70, -1));

        jTextField5base.setText("0");
        getContentPane().add(jTextField5base, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 70, -1));

        jTextField6altura.setText("0");
        getContentPane().add(jTextField6altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 70, -1));

        jButton1.setText("Calcular perimetro");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jButton2.setText("Limpiar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Nombre de la figura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel4.setText("????");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel5perimetro.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5perimetro.setText("Perimetro");
        getContentPane().add(jLabel5perimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel6.setText(".....");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel5.setText("Autor----> Minerva Melissa Trejo Gonzalez");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jLabel3lado1.setVisible(false);
        jLabel4lado2.setVisible(false);
        jLabel5lado3.setVisible(false);
        jLabel6lado4.setVisible(false);
        jLabel7base.setVisible(false);
        jLabel8altura .setVisible(false);
        
        jTextField1lado1.setVisible(false);
        jTextField2lado2.setVisible(false);
        jTextField3lado3.setVisible(false);
        jTextField4lado4.setVisible(false);
        jTextField5base.setVisible(false);
        jTextField6altura.setVisible(false);
        
        buttonGroup1.clearSelection();
        
        jTextField1lado1.setText("0");
        jTextField2lado2.setText("0");
        jTextField3lado3.setText("0");
        jTextField4lado4.setText("0");
        jTextField5base.setText("0");
        jTextField6altura.setText("0");
        
        jLabel4.setText("????");
        jLabel6.setText("....");
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //Al iniciar el formulario 
        //quita los siguients componentes
        jLabel3lado1.setVisible(false);
        jLabel4lado2.setVisible(false);
        jLabel5lado3.setVisible(false);
        jLabel6lado4.setVisible(false);
        jLabel7base.setVisible(false);
        jLabel8altura .setVisible(false);
        
        jTextField1lado1.setVisible(false);
        jTextField2lado2.setVisible(false);
        jTextField3lado3.setVisible(false);
        jTextField4lado4.setVisible(false);
        jTextField5base.setVisible(false);
        jTextField6altura.setVisible(false);
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
        jLabel3lado1.setVisible(true);
        jLabel4lado2.setVisible(true);
        jLabel5lado3.setVisible(true); 
        jTextField1lado1.setVisible(true);
        jTextField2lado2.setVisible(true);
        jTextField3lado3.setVisible(true); 
        
        jLabel4.setText("Triangulo rectangulo");    
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        // TODO add your handling code here:
        jLabel3lado1.setVisible(true);
        jTextField1lado1.setVisible(true);
        jLabel4.setText("Cuadrado");
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
        // TODO add your handling code here:
        jLabel7base.setVisible(true);
        jLabel8altura .setVisible(true);
        jTextField5base.setVisible(true);
        jTextField6altura.setVisible(true);
        jLabel4.setText("Rectangulo");
    }//GEN-LAST:event_jRadioButton3ItemStateChanged

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
        // TODO add your handling code here:
        jLabel3lado1.setVisible(true);
        jTextField1lado1.setVisible(true);
        jLabel4.setText("Rombo");
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5ItemStateChanged
        // TODO add your handling code here:
        jLabel7base.setVisible(true);
        jLabel8altura .setVisible(true);
        jTextField5base.setVisible(true);
        jTextField6altura.setVisible(true);
        jLabel4.setText("Romboide");     
    }//GEN-LAST:event_jRadioButton5ItemStateChanged

    private void jRadioButton6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton6ItemStateChanged
        // TODO add your handling code here:
        jLabel3lado1.setVisible(true);
        jLabel4lado2.setVisible(true);
        jLabel5lado3.setVisible(true);
        jLabel6lado4.setVisible(true);
        
        jTextField1lado1.setVisible(true);
        jTextField2lado2.setVisible(true);
        jTextField3lado3.setVisible(true); 
        jTextField4lado4.setVisible(true);
        jLabel4.setText("Trapecio");
    }//GEN-LAST:event_jRadioButton6ItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        libreriaperimetrofiguras objeto1= new libreriaperimetrofiguras();
        Integer perimetro=0;
        if(jRadioButton1.isSelected()){
            Integer a= Integer.valueOf(jTextField1lado1.getText());
            Integer b= Integer.valueOf(jTextField2lado2.getText());
            Integer c= Integer.valueOf(jTextField3lado3.getText());
            perimetro = objeto1.Perimetrotriangulorectangulo(a, b, c);
            jLabel6.setText(String.valueOf(perimetro));
        }
        else  if(jRadioButton2.isSelected()){
            Integer a= Integer.valueOf(jTextField1lado1.getText());
            perimetro = objeto1.Perimetrocuadrado(a);
            jLabel6.setText(String.valueOf(perimetro));
            
        }
        else  if(jRadioButton3.isSelected()){
            Integer a= Integer.valueOf(jTextField5base.getText());
            Integer b= Integer.valueOf(jTextField6altura.getText());
            perimetro = objeto1.Perimetrorectangulo(a, b);
            jLabel6.setText(String.valueOf(perimetro));
        }
        else  if(jRadioButton4.isSelected()){
             Integer a= Integer.valueOf(jTextField1lado1.getText());
            perimetro = objeto1.Perimetrorombo(a);
            jLabel6.setText(String.valueOf(perimetro));
            
        }
        else  if(jRadioButton5.isSelected()){
            Integer a= Integer.valueOf(jTextField5base.getText());
            Integer b= Integer.valueOf(jTextField6altura.getText());
            perimetro= objeto1.Perimetroromboide(a, b);
            jLabel6.setText(String.valueOf(perimetro));
            
        }
        else  if(jRadioButton6.isSelected()){
            Integer a= Integer.valueOf(jTextField1lado1.getText());
            Integer b= Integer.valueOf(jTextField2lado2.getText());
            Integer c= Integer.valueOf(jTextField3lado3.getText());
            Integer d= Integer.valueOf(jTextField4lado4.getText());
            perimetro = objeto1.Perimetrotrapecio(a, b, c, d);
            jLabel6.setText(String.valueOf(perimetro));   
        }     
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formperimetrosfiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formperimetrosfiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formperimetrosfiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formperimetrosfiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formperimetrosfiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3lado1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4lado2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5lado3;
    private javax.swing.JLabel jLabel5perimetro;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6lado4;
    private javax.swing.JLabel jLabel7base;
    private javax.swing.JLabel jLabel8altura;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1lado1;
    private javax.swing.JTextField jTextField2lado2;
    private javax.swing.JTextField jTextField3lado3;
    private javax.swing.JTextField jTextField4lado4;
    private javax.swing.JTextField jTextField5base;
    private javax.swing.JTextField jTextField6altura;
    // End of variables declaration//GEN-END:variables
}
